s22-4pm-1 Added favicon, navbar icon, and footer copyright info
ucsb-cs156-s22/s22-4pm-courses pull request #56
Opened 2022-06-02 05:37 UTC by AvivSamet

# Overview

Added favicon, added the storke tower icon to the nav bar, and added the copyright text for the storke tower icon to the footer. Tests for the footer were also implemented

# Issues Addressed

Closes #48 

# Link to Storybook

2022-06-02 05:48 UTC, AvivSamet commented
I'm not sure why the production CIs are failing. However, I tried making the changes the eslint CI was asking for and the footer tests failed.

2022-06-02 22:07 UTC, roberto-garcia-0 commented
I am not sure if this bug will be reflected on the deployment. Will have to check that.

2022-06-02 22:17 UTC, roberto-garcia-0 approved these changes
Verified that the qa deployment did not have the same bug as in the localhost deployment.

![Screenshot_20220602_151423](https://user-images.githubusercontent.com/59896939/171747491-02de7671-b786-4b31-84b3-0580d5130992.png)

LGTM!

2022-06-03 08:05 UTC, andrewhlu submitted a review, later dismissed
Tested on Heroku and changes look good! Some clarifying questions before I merge:

1. I saw this comment in your PR description:

> There is currently a bug with the image not rendering in the navbar when the backend is deployed.

Could you elaborate on what this means / provide steps to reproduce this issue? Additionally, is this filed as an actual issue in GitHub so future iterations can work on this?

2. I saw that you had added Storybook support for the navbar, but I don't see a new story for the new footer. Did you plan on adding those here?

2022-06-03 19:28 UTC, AvivSamet commented
> Tested on Heroku and changes look good! Some clarifying questions before I merge:
> 
> 1. I saw this comment in your PR description:
> 
> > There is currently a bug with the image not rendering in the navbar when the backend is deployed.
> 
> Could you elaborate on what this means / provide steps to reproduce this issue? Additionally, is this filed as an actual issue in GitHub so future iterations can work on this?
> 
> 2. I saw that you had added Storybook support for the navbar, but I don't see a new story for the new footer. Did you plan on adding those here?

Bryan just told me that the image not showing on localhost:8080 when the backend is deployed was a known issue. I'm not sure what I can do to fix it. I wasn't planning on adding a storybook for the footer.

2022-06-03 20:23 UTC, roberto-garcia-0 approved these changes
LGTM!

2022-06-03 21:29 UTC, pconrad requested changes
One small fix... the link to the sticker pack has a syntax error I think.

2022-06-03 21:29 UTC, pconrad commented on frontend/src/main/components/Nav/Footer.js
> +        <a data-testid="footer-sticker-link" href="https://www.as.ucsb.edu/sticker-packs/>">www.as.ucsb.edu/sticker-packs/</a>
Check the syntax on this link...

2022-06-03 21:49 UTC, roberto-garcia-0 approved these changes

2022-06-03 22:07 UTC, pconrad approved these changes
LGTM

2022-06-04 22:36 UTC, merged