4pm-2 - kt - psid sections endpoint
ucsb-cs156-s22/s22-4pm-courses pull request #61
Opened 2022-06-02 22:22 UTC by kthanigaivelan

In this PR, we add the endpoint to get section information given a personal schedule id.
Note: This PR is an update of PR https://github.com/ucsb-cs156-s22/s22-4pm-courses/pull/53 , since I had to use a new branch to get the updates done in main.
Closes Issue https://github.com/ucsb-cs156-s22/s22-4pm-courses/issues/22

2022-06-02 23:15 UTC, archananeupane approved these changes
LGTM!

2022-06-03 08:01 UTC, andrewhlu requested changes

2022-06-03 08:01 UTC, andrewhlu commented on src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
> +        //System.out.println("url=" + url);
this comment seems unnecessary, can we remove it?

2022-06-03 08:01 UTC, andrewhlu commented on src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
> +//import edu.ucsb.cs156.courses.testconfig.SecurityConfig;
^^ see above

2022-06-03 08:01 UTC, andrewhlu commented on src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
please alphabetize and group similar imports if possible! this makes the import list much easier to read

2022-06-03 08:01 UTC, andrewhlu commented on src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsControllerTests.java
> +        //String expectedResponse = "{\"type\":\"EntityNotFoundException\",\"message\":\"PersonalSchedule with id 13 not found\"}";
please remove commented code!

2022-06-03 18:12 UTC, kthanigaivelan commented on src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSectionsController.java
> +        Iterable<Courses> courses = coursesRepository.findAllByPsId(psId); //.orElseThrow(() -> new EntityNotFoundException(Courses.class,"psId", psId ));
Nope, I just removed it!

2022-06-04 22:43 UTC, pconrad approved these changes
LGTM

2022-06-05 02:00 UTC, merged