Update README.md
ucsb-cs156-s22/s22-4pm-courses pull request #7
Opened 2022-05-24 21:47 UTC by archananeupane

in this PR, we added the heroku app link.

2022-05-24 21:48 UTC, kthanigaivelan submitted a review, later dismissed
LGTM!

2022-05-24 22:02 UTC, andrewpengucsb requested changes
Changes are missing a link to the heroku dashboard

Also, the naming does not follow the naming scheme in the instructions. 

"Someone on the -2 or -4 team for each repo should make a production deployment of the repo that has the same name as the repo (e.g. https://s22-5pm-happycows.herokuapp.com/)."

2022-05-25 00:20 UTC, andrewhlu requested changes

2022-05-25 00:20 UTC, andrewhlu commented on README.md
> + https://proj01-s22-4pm-courses.herokuapp.com/
Hi! In addition to adding the link to the deployed app on Heroku, can you also add a link to the Heroku dashboard?

[See relevant section of proj01 instructions](https://ucsb-cs156.github.io/s22/lab/proj01/#:~:text=Make%20an%20issue%2C%20branch%2C%20and%20PR%20to%20a%20link%20to%20the%20deployed%20app%20and%20a%20link%20to%20the%20Heroku%20dashboard%20into%20the%20README.md%20for%20the%20repo.)

2022-05-25 00:21 UTC, andrewhlu commented on README.md
> + https://proj01-s22-4pm-courses.herokuapp.com/
Oops... looks like @andrewpengucsb already mentioned this as a comment up above. Sorry for the duplicate review!

2022-05-26 21:27 UTC, pconrad requested changes
Please fix the title.  I was looking for the PR that sets up the production Heroku deployment so that I could award points for setting up OAuth.   It was really hard to find, because the title is not descriptive.

We don't just ask these things (like descriptive titles) to be annoying—they actually matter. :-)

2022-05-26 22:02 UTC, closed without merging